import 'package:get/get.dart';

class LangController extends GetxController{
  bool isEn=true;

  Map<String,String> getArText={
    'email' :'البريد الالكتروني',
    'password' :'كلمه المرور',
    'save_login_data':'حفظ معلومات التسجيل',
    'login':'تسجيل الدخول',
    'login_as_visitor':'الدخول كزائر',
    'forget_password':'نسيت كلمه المرور',
    'create_new_account':'انشاء حساب جديد',
    'register_as_user':'التسجيل كمستخدم',
    'register_as_trader':'التسجيل كتاجر',
    'confirm':'تاكيد',
    'user_name':'اسم المستخدم',
    'phone':'رقم الهاتف',
    'confirm_password':'تاكيد كلمه المرور',
    'store_name':'اسم المتجر',
    'main_page':'الصفحة الرئيسية',
    'stores':'المتاجر',
    'watches':'الساعات',
    'bracletes':'الاساور',
    'user_name':'اسم المستخدم',
    'add_ads':'اضافه اعلان',
    'my_account':'حسابي',
    'favorites':'المفضله',
    'my_ads':'اعلاناتي',
    'messages':'الرسائل',
    'setting':'الاعدادات',
    'about_app':'عن التطبيق',
    'about_us':'من نحن',
     'call_us':'اتصل بنا',
    'log_out':'تسجيل الخروج',
    'welcome_as_visitor':'مرحبا بك كزائر لساعاتي',
    'watch':'ساعة',
    'braclete':'اسورة',
    'currency':'ريال سعودي',
    'new':'جديد',
    'old':'مستعمل',
    'search':'بحث',
    'arrange':'ترتيب حسب:',
    'filter':'فرز حسب:',
    'from_high':'من أعلي سعر الي اقل سعر :',
    'from_low':'من أقل سعر الي اعلي سعر :',
    'new_prods':'منتجات جديده',
    'old_prods':'منتجات مستعمله',
    'execute':'تنفيد',
    'prod_images':'صور المنتج',
    'trader_name':'اسم التاجر',
    'store_name':'اسم المتجر',
    'send_messages_to_trader':'ارسال رساله الي التاجر',
    'message_title':'عنوان الرساله',
    'message_content':'نص الرساله',
    'send':'ارسال',
    'category':':القسم',
    'status':'الحاله:',
    'prod_name':'اسم المنتج :',
    'prod_price':'سعر المنتج:',
    'phone_conn':'رقم الهاتف للتواصل',
    'email_conn':'البريد الالكتروني للتواصل:',
    'conn_type':'طريقه التواصل :',
    'private_messages':'الرسائل الخاصة',
    'all':'الكل',
    'prod_desc':'وصف بيانات المنتج مع ذكر الضمان',
    'attatch_prod_images':'ارفاق صور المنتج:',
    'save':'حفظ',
    'message_send':'الوارده',
    'message_receive':'الصادرة',
    'delete':'مسح',
    'cancel':'الغاء'
  };
  Map<String,String> getEnText={
    'email' :'Email',
    'password' :'Password',
    'save_login_data':'Save Login Data',
    'login':'Login',
    'login_as_visitor':'Login As Visitor',
    'forget_password':'Forget Password?',
    'create_new_account':'Create New Account',
    'register_as_user':'Register As User',
    'register_as_trader':'Register As Trader',
    'confirm':'Confirm',
    'user_name':'User Name',
    'phone':'Phone',
    'confirm_password':'Confirm Password',
    'store_name':'',
    'main_page':'',
    'stores':'',
    'watches':'',
    'bracletes':'',
    'user_name':'',
    'add_ads':'',
    'my_account':'',
    'favorites':'',
    'my_ads':'',
    'messages':'',
    'setting':'',
    'about_app':'',
    'about_us':'',
    'call_us':'',
    'log_out':'',
    'welcome_as_visitor':'',
    'watch':'',
    'braclete':'',
    'currency':'',
    'new':'',
    'old':'',
    'search':'',
    'arrange':'',
    'filter':'',
    'from_high':'',
    'from_low':'',
    'new_prods':'',
    'old_prods':'',
    'execute':'',
    'prod_images':'',
    'trader_name':'',
    'store_name':'',
    'send_messages_to_trader':'',
    'message_title':'',
    'message_content':'',
    'send':'',
    'category':'',
    'prod_name':'',
    'prod_price':'',
    'phone_conn':'رقم الهاتف للتواصل',
    'email_conn':'',
    'conn_type':'',
    'private_messages':'',
    'all':'',
    'prod_desc':'وصف بيانات المنتج مع ذكر الضمان',
    'attatch_prod_images':'',
    'save':'',
    'message_send':'',
    'message_receive':'',
    'delete':'',
    'cancel':''
  };


  changeLang(bool newVal){
    isEn=newVal;
    update();
  }

  getText(String key) {
    if (isEn == true) {
      return getEnText[key];
    }else{
      return getArText[key];
    }
  }


}