import 'package:get/get.dart';

class LangController extends GetxController{
  bool isEn=false;

  Map<String,String> getArText={
    'email' :'البريد الالكتروني',
    'password' :'كلمه المرور',
    'save_login_data':'حفظ معلومات التسجيل',
    'login':'تسجيل الدخول',
    'login_user':'الدخول كمستخدم',
    'weak_password':'كلمه المرور ضعيفه',
    'login_as_visitor':'الدخول كزائر',
    'forget_password':' نسيت كلمه المرور',
    'create_new_account':'انشاء حساب جديد',
    'register_as_user':'التسجيل كمستخدم',
    'register':'تسجيل',
    'confirm':'تاكيد',
    'user_name':'اسم المستخدم',
    'phone':'رقم الهاتف',
    'confirm_password':'تاكيد كلمه المرور',
    'store_name':'اسم المتجر',
    'main_page':'الصفحة الرئيسية',
    'stores':'المتاجر',
    'watches':'الساعات',
    'bracletes':'الاساور',
    'user_name':'اسم المستخدم',
    'add_ads':'اضافه اعلان',
    'my_account':'حسابي',
    'favorites':'المفضله',
    'my_ads':'اعلاناتي',
    'messages':'الرسائل',
    'setting':'الاعدادات',
    'about_app':'عن التطبيق',
    'about_us':'من نحن',
     'call_us':'اتصل بنا',
    'log_out':'تسجيل الخروج',
    'welcome_as_visitor':'مرحبا بك كزائر لساعاتي',
    'watch':'ساعة',
    'braclete':'اسورة',
    'currency':'ريال سعودي',
    'new':'جديد',
    'old':'مستعمل',
    'search':'بحث',
    'arrange':'ترتيب حسب:',
    'filter':'فرز حسب:',
    'from_high':'من أعلي سعر الي اقل سعر :',
    'from_low':'من أقل سعر الي اعلي سعر :',
    'new_prods':'منتجات جديده',
    'old_prods':'منتجات مستعمله',
    'execute':'تنفيد',
    'prod_images':'صور المنتج',
    'trader_name':'اسم التاجر',
    'store_name':'اسم المتجر',
    'send_messages_to_trader':'ارسال رساله الي التاجر',
    'message_title':'عنوان الرساله',
    'message_content':'نص الرساله',
    'send':'ارسال',
    'category':':القسم',
    'status':'الحاله:',
    'prod_name':'اسم المنتج :',
    'prod_price':'سعر المنتج:',
    'phone_conn':'رقم الهاتف للتواصل',
    'email_conn':'البريد الالكتروني للتواصل:',
    'conn_type':'طريقه التواصل :',
    'private_messages':'الرسائل الخاصة',
    'all':'الكل',
    'prod_desc':'وصف بيانات المنتج مع ذكر الضمان',
    'attatch_prod_images':'ارفاق صور المنتج:',
    'save':'حفظ',
    'message_send':'الوارده',
    'message_receive':'الصادرة',
    'delete':'مسح',
    'cancel':'الغاء',
  'change_lang':'اختر لغتك المفضله',
  'lang':'العربية',
    'language':'اللغة',
    'setting':'الاعدات',
    'enter_email' :'ادخل البريد الالكتروني',
    'not_valid_mail':'بريد الكتروني غير صحيح'
  };
  Map<String,String> getEnText={
    'email' :'Email',
    'password' :'Password',
    'save_login_data':'Save Login Data',
    'login':'Login',
    'login_user':'Login User',
    'login_as_visitor':'Login As Visitor',
    'forget_password':'Forget Password?',
    'weak_password':'Weak Password',
    'create_new_account':'Create New Account',
    'register_as_user':'Register As User',
    'register_as_trader':'Register As Trader',
    'register':'Register',
    'confirm':'Confirm',
    'user_name':'User Name',
    'phone':'Phone',
    'confirm_password':'Confirm Password',
    'store_name':'Store Name',
    'main_page':'Main Page',
    'stores':'Stores',
    'watches':'Watches',
    'bracletes':'Bracletes',
    'user_name':'User Name',
    'add_ads':'Add Ads',
    'my_account':'My Account',
    'favorites':'Favorites',
    'my_ads':'My Ads',
    'messages':'Messages',
    'setting':'Setting',
    'about_app':'About App',
    'about_us':'About Us',
    'call_us':'Call Us',
    'log_out':'LogOut',
    'welcome_as_visitor':'Welcome As Visitor',
    'watch':'Watch',
    'braclete':'Braclet',
    'currency':'Currency',
    'new':'New',
    'old':'Old',
    'search':'Search',
    'arrange':'Arrange',
    'filter':'Filter',
    'from_high':'From High',
    'from_low':'From Low',
    'new_prods':'New Products',
    'old_prods':'Old Products',
    'execute':'Execute',
    'prod_images':'Product Images',
    'trader_name':'Trader Name',
    'store_name':'Store Name',
    'send_messages_to_trader':'Send Messages To Trader',
    'message_title':'Message Title',
    'message_content':'Message Content',
    'send':'Send',
    'category':'Category',
    'prod_name':'Name',
    'prod_price':'Price',
    'phone_conn':'Phone',
    'email_conn':'Email',
    'conn_type':'Connection Type',
    'private_messages':'Private Messages',
    'all':'All',
    'prod_desc':'description of product and grantee',
    'attatch_prod_images':'Attatch Images of Product',
    'save':'Save',
    'message_send':'Send',
    'message_receive':'Recevied',
    'delete':'Delete',
    'cancel':'Cancel',
    'change_lang':'Change To Preferred Language',
    'lang':'English',
    'language':'Language',
    'setting':'ٍSetting',
    'enter_email' :'Enter Email',
    'not_valid_mail':'not valid mail'

  };


  changeLang(bool newVal){
    isEn=newVal;
    update();
  }

  getText(String key) {
    if (isEn == true) {
      return getEnText[key];
    }else{
      return getArText[key];
    }
  }


}