import 'package:get/get.dart';

class LocaleString extends Translations{

  Map<String ,Map<String,String>> get keys =>{
    'en': {
      'add_to_cart':'ADD TO CART',
      'address':'Address',
      'website':'WebSite',
      'send_message':'Send Message',
  'email' :'Email',
      'home':'Home',
  'password' :'Password',
  'save_login_data':'Save Login Data',
  'login':'Login',
      'all':'All',
  'login_user':'Login User',
  'login_as_visitor':'Login As Visitor',
  'forget_password':'Forget Password?',
  'weak_password':'Weak Password',
      'password_not_match':'Password Not Matched',
  'create_new_account':'Create New Account',
  'register_as_user':'Register As User',
  'register_as_trader':'Register As Trader',
  'register':'Register',
  'confirm':'Confirm',
  'user_name':'User Name',
      'name':'Name',
      'user':'User',
  'phone':'Phone',
  'confirm_password':'Confirm Password',
  'store_name':'Store Name',
  'main_page':'Main Page',
  'stores':'Stores',
  'watches':'Watches',
  'bracletes':'Bracletes',
  'user_name':'User Name',
  'add_ads':'Add Ads',
  'my_account':'My Account',
  'favorites':'Favorites',
  'my_ads':'My Ads',
  'messages':'Messages',
  'setting':'Setting',
  'about_app':'About App',
  'about_us':'About Us',
  'call_us':'Call Us',
  'log_out':'LogOut',
  'welcome_as_visitor':'Welcome As Visitor',
  'watch':'Watch',
  'braclete':'Braclet',
  'currency':'PSD',
  'new':'New',
  'old':'Old',
  'search':'Search',
  'arrange':'Arrange Where:',
  'filter':'Filter where:',
  'from_high':'From High',
  'from_low':'From Low',
  'new_prods':'New Products',
  'old_prods':'Old Products',
  'execute':'Execute',
  'prod_images':'Product Images',
  'trader_name':'Trader Name',
  'store_name':'Store Name',
  'send_messages_to_trader':'Send Messages To Trader',
  'message_title':'Message Title',
  'message_content':'Message Content',
  'send':'Send',
  'category':'Category: ',
      'status':'Status: ',
  'prod_name':'Name',
  'prod_price':'Price',
  'phone_conn':'Owner Phone',
  'email_conn':'Owner Email',
  'conn_type':'Connection Type',
  'private_messages':'Private Message',
  'all':'All',
  'prod_desc':'description of product and grantee',
  'attatch_prod_images':'Attatch Images of Product',
  'save':'Save',
  'message_send':'Send',
  'message_receive':'Recevied',
  'delete':'Delete',
  'cancel':'Cancel',
  'change_lang':'Change To Preferred Language',
      'choose_lang':'Choose Language',
  'lang':'English',
  'language':'Language',
  'setting':'ٍSetting',
  'enter_email' :'Enter Email',
  'not_valid_mail':'not valid mail',
      'empty_data':'No Data Found',
      'create_product':'Create Product',
      'reply':'ٌReply',
      'select_all':'Select All',
      'cancel_all':'Cancel All',
      'send_message':'Send Message',
      'send_message_sucessfully':'Sending Message Sucessfully',
      'inavlid_email':'enter valid email',
      'catgory':'Category',
      'new_password':'New Password',
      'old_password':'Old Password',
      'change_password':'Change Password',
      'delete_item':'Delete Item',
      'are_you_sure_delete':'Are you Sure Delete this Item',
      'ok':'Ok',
      'order_now':'Order Now',
  'total':'Total:',
    },




    'ar':{
      'order_now':'اطلب الان',
      'total':' الاجمالي:',
      'ok':'تم',
  'are_you_sure_delete':'هل انت متاكد من حذف هذا العنصر',
      'add_to_cart':'اضافه للعربة',
      'name':'الاسم',
      'new_password':'كلمه المرور الجديده',
  'old_password':'كلمه المرور القديمة',
      'address':'العنوان',
      'website':'الموقع',
      'catgory':'الاقسام',
      'email' :'البريد الالكتروني',
  'password' :'كلمه المرور',
      'home':'الرئيسيه',
      'all':'الكل',
  'save_login_data':'حفظ معلومات التسجيل',
  'login':'تسجيل الدخول',
  'login_user':'الدخول كمستخدم',
  'weak_password':'كلمه المرور ضعيفه',
  'login_as_visitor':'الدخول كزائر',
      'password_not_match':'كلمه المرور غير متطابقه',
  'forget_password':' نسيت كلمه المرور',
  'create_new_account':'انشاء حساب جديد',
  'register_as_user':'التسجيل كمستخدم',
      'register_as_trader':'التسجيل كتاجر',
  'register':'تسجيل',
  'confirm':'تاكيد',
  'user_name':'اسم المستخدم',
  'phone':'رقم الهاتف',
  'confirm_password':'تاكيد كلمه المرور',
  'store_name':'اسم المتجر',
  'main_page':'الصفحة الرئيسية',
  'stores':'المتاجر',
  'watches':'الساعات',
  'bracletes':'الاساور',
  'user_name':'اسم المستخدم',
  'add_ads':'اضافه اعلان',
  'my_account':'حسابي',
  'favorites':'المفضله',
  'my_ads':'اعلاناتي',
  'messages':'الرسائل',
  'setting':'الاعدادات',
  'about_app':'عن التطبيق',
  'about_us':'من نحن',
  'call_us':'اتصل بنا',
  'log_out':'تسجيل الخروج',
  'welcome_as_visitor':'مرحبا بك كزائر لساعاتي',
  'watch':'ساعة',
  'braclete':'اسورة',
      'delete_item':'حذف العنصر',
  'currency':'ريال',
  'new':'جديد',
  'old':'مستعمل',
  'search':'بحث',
  'arrange':'ترتيب حسب:',
  'filter':'فرز حسب:',
  'from_high':'من أعلي سعر الي اقل سعر :',
  'from_low':'من أقل سعر الي اعلي سعر :',
  'new_prods':'منتجات جديده',
  'old_prods':'منتجات مستعمله',
  'execute':'تنفيد',
  'prod_images':'صور المنتج',
  'trader_name':'اسم التاجر',
  'store_name':'اسم المتجر',
  'send_messages_to_trader':'ارسال رساله الي التاجر',
  'message_title':'عنوان الرساله',
  'message_content':'نص الرساله',
  'send':'ارسال',
      'send_message':'ارسال رساله',
  'category':'القسم:',
  'status':'الحاله:',
  'prod_name':'اسم المنتج :',
      'enter_name':'ادخل الاسم :',
      'enter_price':'ادخل السعر :',
      'inavlid_email':'ادخل ايميل صحيح',

  'prod_price':'سعر المنتج:',
  'phone_conn':'رقم الهاتف للتواصل',
  'email_conn':'البريد الالكتروني للتواصل:',
  'conn_type':'طريقه التواصل :',
  'private_messages':'الرسائل الخاصة',
  'all':'الكل',
  'prod_desc':'وصف بيانات المنتج مع ذكر الضمان',
  'attatch_prod_images':'ارفاق صور المنتج:',
  'save':'حفظ',
  'message_send':'الوارده',
  'message_receive':'الصادرة',
  'delete':'مسح',
  'cancel':'الغاء',
  'change_lang':'اختر لغتك المفضله',
      'choose_lang':'اختر اللغة',
  'lang':'العربية',
  'language':'اللغة',
  'setting':'الاعدات',
  'enter_email' :'ادخل البريد الالكتروني',
  'not_valid_mail':'بريد الكتروني غير صحيح',
      'empty_data':'لا توجد بيانات',
      'create_product':'انشاء منتج',
      'reply':' رد برساله',
      'select_all':'تحديد الكل',
      'cancel_all':'الغاء الكل',
      'send_message_sucessfully':'تم ارسال الرساله بنجاح',
      'change_password':'تغيير كلمه المرور'
    }

  };


}